export const styleApp2 = {
  ctnItem: {flex: 1, marginTop: 10},
  ctnAvtItem: {flexDirection: 'row', alignItems: 'center', marginLeft: 10},
  avtItem: {height: 50, width: 50, borderRadius: 25},
  name: {fontSize: 17, fontWeight: 'bold', marginLeft: 15},
  picUpload: {height: 400, width: '100%', marginTop: 10},
  ctnTool: {flexDirection: 'row', marginTop: 10},
  iconTool: {fontSize: 30, marginLeft: 15},
  line: {
    width: '100%',
    backgroundColor: 'gray',
    height: 0.5,
    marginTop: 10,
  },
  ctnCountLike: {
    marginLeft: 15,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconLiked: {fontSize: 30},
  txtCountLike: {fontSize: 15, fontWeight: 'bold', marginLeft: 10},
  ctnLogo: {
    flexDirection: 'row',
    backgroundColor: '#f3f6fa',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginLeft: 27,
  },
  imgLogo: {
    flex: 1,
    height: 44,
  },
  iconInbox: {fontSize: 27, marginRight: 5},
};
