export const styleApp = {
  containerItem: {flex: 1},
  imgItem: {width: 150, height: 150},
  ctnHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 30,
    marginTop: 10,
  },
  iconHeader: {fontSize: 30, color: 'gray'},
  ctnAvt: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 30,
  },
  avt: {width: 100, height: 100, borderRadius: 50},
  name: {fontSize: 30, fontWeight: 'bold'},
  colorGray: {color: 'gray'},
  ctnContact: {
    marginTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  ctnButton: {
    backgroundColor: 'rgb(71,113,246)',
    width: 90,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  txtFollow: {fontSize: 15, color: '#FFF'},
  ctnSend: {
    backgroundColor: 'rgb(120,213,250)',
    width: 45,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  iconSend: {color: '#FFF', fontSize: 15},
  ctnViewFollow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 30,
    marginTop: 20,
  },
  ctnCenter: {alignItems: 'center'},
  txtCount: {fontSize: 20, fontWeight: 'bold'},
  flatList: {marginHorizontal: 30, marginTop: 20},
  ctnBottom: {alignItems: 'center', justifyContent: 'center', height: 40},
  ctnBotChild: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: 200,
  },
  iconBottom: {fontSize: 25, color: 'gray'},
};
